[book]
authors = ["bananaturtlesandwich/spuds"]
language = "en"
multilingual = false
src = "src"
title = "UE4 Modding Guide"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/bananaturtlesandwich/UE4-Modding-Guide"
edit-url-template = "https://github.com/bananaturtlesandwich/UE4-Modding-Guide/edit/main/{path}"