name: Deploy website

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: '42 16 1/7 * *'

env:
  MDBOOK_LINKCHECK_VER: 0.7.6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy MDBook
        # You may pin to the exact commit or the version.
        # uses: XAMPPRocky/deploy-mdbook@508792eaea5817897ccdfc1b5b7047dbe9ec5a5c
        uses: XAMPPRocky/deploy-mdbook@v1
        with:
          # The github reposistory in `owner/repo` format.
          repository: bananaturtlesandwich/Blue-Fire-Modding-Guide
          # The GitHub token for deploying mdbook.
          token: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGw3T1Zhzo4YPx7fFNBxD1/MBlOG4rKKbX2SxL9m9T+a afcarreyette@gmail.com
